shuffle_train = False
train_eval_random_subset = True
RELATIONTYPE_AMOUNT = 500
ENTITYTYPE_AMOUNT = 5000
ATTRIBUTES_AMOUNT = 1000
FACTS_PER_IMPLICATION = 800
NUMBER_RULES = 20
IMPLICATIONS_PER_RELATION = 2
FACTS_PER_RELATION_DISTRACTION_PATTERNS = 800
MAX_INSTANCES_PER_FACT = 1
ratio_of_pattern_relations = 0.5  # percentage of relations that show the specific pattern
ratio_of_complete_patterns = 0.9  # for the relations that show pattern, how many patterns are complete in training
